# the source tree needs to be "booted" for this stack.yaml file to be usable:
#
# $ git submodule update --init --recursive
# $ ./utils/makePackages.sh
#

resolver: lts-13.22
packages:
  - .
  - ./lib/ghc-api-ghcjs
  - ./lib/ghci-ghcjs
  - ./lib/ghcjs-th
  - ./lib/haddock-api-ghcjs
  - ./lib/haddock-library-ghcjs
  - ./lib/template-haskell-ghcjs
extra-deps:
  - yaml-0.10.4.0
